### ISSUE TITLE
Documentation refers to the unexistent stable 2.0 release of the extension

### ISSUE THREAD

**Issue by akovalyov** [sensiolabs/BehatPageObjectExtension#58]
It tells about that user should add ```"sensiolabs/behat-page-object-extension": "~2.0"``` in ```require-dev``` section. However, such release does not exist yet. So, either the version constraint should be changed to ```2.0.*@dev``` in the doc or it is time to tag a new release.
@jakzal what do you think?

**Comment by PG2000** [comment]
@jakzal ping

**Comment by jakzal** [comment]
I'll work on tagging stable release soon. Sorry for the delay :)

**Comment by peterfox** [comment]
Can we please get a stable release, really causes me headache because there's no stable release that works with Behat 3.0

**Comment by netdiablo** [comment]
Any ETA on this? I just tried to install the extension (using Behat 3.0.15) and got:
`Potential causes:`
`A typo in the package name`
`The package is not available in a stable-enough version[...]`
Thanks.

**Comment by icambridge** [comment]
Can a tag not just be made? The project hasn't had any activity since October so it's not like this project is going to become any more stable any time soon. So why not have a tag which we can use instead of us either having to use `dev-master` which is bad practice, use an older version of behat, or not use this?

**Comment by jakzal** [comment]
I just merged #63. If any of you guys could confirm it works with your projects would be fab.

**Comment by icambridge** [comment]
I can confirm it works for me.

**Comment by dkontorovsky** [comment]
Followed instructions on http://behat-page-object-extension.readthedocs.org/en/latest/guide/installation.html. The issue is still there :-( It only works if using dev-master instead of "~2.0" ("require-dev")

**Comment by jakzal** [comment]
@dkontorovsky that's not gonna work until we tag the release. Until then use `dev-master`. I kindly asked you to review docs as I updated them and want them to be accurate for the release :)

**Comment by jakzal** [comment]
[v2.0.0-rc1](https://github.com/sensiolabs/BehatPageObjectExtension/releases/tag/v2.0.0-rc1) was just tagged.

**Comment by jakzal** [comment]
If everyone's fine with rc1 I'll release v2.0.0 in couple of days.

**Comment by icambridge** [comment]
:+1:

**Comment by timbordemann** [comment]
Any news on this? It would be great being able to specify a stable version in composer.json :)

**Comment by jakzal** [comment]
@timbordemann it would help if you tested latest version from master :)

**Comment by jakzal** [comment]
[v2.0.0](https://github.com/sensiolabs/BehatPageObjectExtension/releases/tag/v2.0.0) was just tagged.
